name: advent-of-code
channels:
  - defaults
  - conda
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aom=3.12.1=ha237518_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - dav1d=1.2.1=h80987f9_0
  - expat=2.7.3=h982b769_0
  - fontconfig=2.15.0=h29935d0_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.2=h80987f9_0
  - graphite2=1.3.14=hc377ac9_1
  - harfbuzz=10.2.0=he637ebf_1
  - icu=73.1=h313beb8_0
  - jpeg=9f=h2f69dba_0
  - lcms2=2.17=h7418793_0
  - leptonica=1.82.0=hdedf53e_3
  - lerc=4.0.0=h313beb8_0
  - libarchive=3.8.2=ha845c4f_0
  - libavif=1.3.0=h839b4eb_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libglib=2.84.4=h7a3292d_0
  - libhwloc=2.12.1=default_h2915d5d_1000
  - libiconv=1.16=h80987f9_3
  - libllvm20=20.1.8=h1701f07_0
  - libopenblas=0.3.30=hf2bb037_2
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.50=h5c318fc_0
  - libtiff=4.7.1=h367c460_0
  - libwebp=1.6.0=h30d73d9_0
  - libwebp-base=1.6.0=h92b2d59_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - llvmlite=0.45.1=py312hc8eb11b_0
  - lz4-c=1.9.4=h313beb8_1
  - ncurses=6.5=hee39554_0
  - numba=0.62.1=py312h471b49b_0
  - numpy=2.3.5=py312h4bb6f22_0
  - numpy-base=2.3.5=py312h23175f9_0
  - openjpeg=2.5.4=h959fc53_1
  - openssl=3.0.18=h9b4081a_0
  - packaging=25.0=py312hca03da5_1
  - pcre2=10.46=h1dacb4a_0
  - pillow=12.0.0=py312he2d6fe4_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - pytesseract=0.3.10=py312hca03da5_1
  - python=3.12.12=h2bfc596_1
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py312hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tbb=2022.3.0=h50665e7_0
  - tesseract=5.2.0=h9e66425_3
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py312hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/advent-of-code
